# Generated by Django 4.1.6 on 2024-04-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Constructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='coordinates',
            field=models.TextField(null=True),
        ),
    ]
