# Generated by Django 4.1.6 on 2024-05-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Constructor', '0002_line_name_alter_line_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('winter', 'Зима'), ('spring', 'Весна'), ('summer', 'Лето'), ('autumn', 'Осень'), ('any', 'Любой')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='difficulty',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='seasons',
            field=models.ManyToManyField(to='Constructor.season'),
        ),
    ]
