# Generated by Django 4.1.6 on 2024-05-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Constructor', '0003_season_line_difficulty_line_length_line_seasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='seasons',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.AddField(
            model_name='line',
            name='seasons',
            field=models.TextField(null=True),
        ),
    ]
