# Generated by Django 4.1.6 on 2024-05-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Constructor', '0005_line_notes'),
        ('Constructor', '0005_line_popularity'),
    ]

    operations = [
    ]
