# Generated by Django 4.1.6 on 2024-06-05 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Constructor', '0007_line_author_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_id', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('name', models.TextField(null=True)),
                ('participants', models.TextField(null=True)),
                ('route_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Constructor.line')),
            ],
        ),
    ]
