# Generated by Django 4.1.6 on 2024-06-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Userprofile", "0004_userprofile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="personal_photo",
            field=models.ImageField(
                default="userprofile/assets/png/png1.jpg",
                upload_to="userprofile/profile_photos/",
            ),
        ),
    ]
