# Generated by Django 4.1.6 on 2024-06-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Userprofile", "0006_alter_userprofile_personal_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="personal_photo",
            field=models.ImageField(
                default="def/anonim.avif", upload_to="profile_photos/"
            ),
        ),
    ]
